export const authOperations: {[key: string]: number[]} = {
  dashboardDevices: [1, 2, 3],
  ramUsage: [1, 2, 3],
  cpuTemperature: [1, 2, 3],
  cpuUsage: [1, 2, 3],
  diskUsage: [1, 2, 3],
  loadAverage: [1, 2, 3],
  networkStats: [1, 2, 3],
  dashboardDeviceDataRT: [1, 2, 3],
  deviceReadingSettings: [1, 2],
  deviceReadingSettingsByIdDevice: [1, 2],
  updateDeviceReadingSettings: [1, 2],
  devices: [1, 2],
  device: [1, 2],
  createDevice: [1, 2],
  updateDevice: [1, 2],
  deleteDevice: [1 ,2],
  roles: [1, 2, 3],
  users: [1],
  user: [1],
  permissions: [1, 2, 3],
  createUser: [1],
  updateUser: [1],
  deleteUser: [1]
}